## 1. Creating Matrices

#### <span style="color:blue">1.1 Creating matrices using numpy library</span>

In [1]:
import numpy as np
A = np.array([[2,1,0],[1,-1,2]]) #Create Matrix A of size 2x3
print(A)

[[ 2  1  0]
 [ 1 -1  2]]


In [2]:
B = np.array([[1,1,3],[2,1,0]])
print(B)

[[1 1 3]
 [2 1 0]]


#### <span style="color:blue">1.2 Creating Matrices using sympy library</span>

In [3]:
import sympy as sp
#sp.init_printing()

M = sp.Matrix([[-1,7,-1],[0,1,0],[0,15,-2]])
M

Matrix([
[-1,  7, -1],
[ 0,  1,  0],
[ 0, 15, -2]])

In [4]:
#Create matrix by providing dimension
N = sp.Matrix(3,3,[0,0,-2,1,2,1,1,0,3])
N

Matrix([
[0, 0, -2],
[1, 2,  1],
[1, 0,  3]])

In [5]:
P = sp.Matrix(5,3,[1,2,3,1,2,3,3,2,1,3,4,5,3,2,1])
display(P)

Matrix([
[1, 2, 3],
[1, 2, 3],
[3, 2, 1],
[3, 4, 5],
[3, 2, 1]])

#### <span style="color:blue;">1.3 Assessing rows and columns of a matrix</span>

In [6]:
P.row(-4)

Matrix([[1, 2, 3]])

In [7]:
P.col(1)

Matrix([
[2],
[2],
[2],
[4],
[2]])

In [8]:
#Accessing 3 row 3rd element
P.row(2)[2]

1

In [9]:
P.col(1)[3]

4

#### <span style="color:blue;">1.4 Deleting and inserting rows and columns</span>

In [26]:
A = sp.Matrix(4,5,[1,5,3,9,0,-2,1,3,-7,3,2,7,1,0,-1,3,6,5,4,2])
A

Matrix([
[ 1, 5, 3,  9,  0],
[-2, 1, 3, -7,  3],
[ 2, 7, 1,  0, -1],
[ 3, 6, 5,  4,  2]])

In [27]:
A.row_del(1)
A

Matrix([
[1, 5, 3, 9,  0],
[2, 7, 1, 0, -1],
[3, 6, 5, 4,  2]])

In [28]:
A.col_del(3)
A

Matrix([
[1, 5, 3,  0],
[2, 7, 1, -1],
[3, 6, 5,  2]])

In [29]:
B = sp.Matrix(5,4,[1,9,8,3,2,0,9,0,1,0,2,7,3,5,0,1,2,5,3,6])
B

Matrix([
[1, 9, 8, 3],
[2, 0, 9, 0],
[1, 0, 2, 7],
[3, 5, 0, 1],
[2, 5, 3, 6]])

In [30]:
C = B.row_insert(0,sp.Matrix([[-1,0,1,0]]))
C

Matrix([
[-1, 0, 1, 0],
[ 1, 9, 8, 3],
[ 2, 0, 9, 0],
[ 1, 0, 2, 7],
[ 3, 5, 0, 1],
[ 2, 5, 3, 6]])

In [31]:
D = B.col_insert(4,sp.Matrix([-1,1,0,1,-1]))
D

Matrix([
[1, 9, 8, 3, -1],
[2, 0, 9, 0,  1],
[1, 0, 2, 7,  0],
[3, 5, 0, 1,  1],
[2, 5, 3, 6, -1]])

#### <span style="color:blue;">1.5 Getting dimension/size of the matrix</span>

In [32]:
sp.shape(B)

(5, 4)

#### <span style="color:blue;">1.7 Matrix constructors for common matrices</span>

In [34]:
#Create identity matrix of size 3

M1 = sp.eye(3)
M1

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [35]:
M2 = sp.zeros(2,3)
M2

Matrix([
[0, 0, 0],
[0, 0, 0]])

In [36]:
M3 = sp.ones(4,5)
M3

Matrix([
[1, 1, 1, 1, 1],
[1, 1, 1, 1, 1],
[1, 1, 1, 1, 1],
[1, 1, 1, 1, 1]])

In [37]:
M4 = sp.diag(1,2,3,4)
M4

Matrix([
[1, 0, 0, 0],
[0, 2, 0, 0],
[0, 0, 3, 0],
[0, 0, 0, 4]])